dataset: cifar10
n_classes: 10
n_channels: 3
img_size: 32
data_root: /home/rizawa/Codes/recruitement/assignment/data
test: False
lr: 0.0001
resume: False
seed: 2
batch_size: 64
n_epochs: 50
decay: 1e-4
log_dir: ./logs/
n_gpus: 4

